POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhYzRkNzIyZGU0ZjNiNGExY2QzNTFhMyIsImlhdCI6MTc5MTMwNDM2MH0.3glMbbu2kJ0YkdwjXe2i9NLzRjIiI-lBCWmHgDbCxuY

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true,
  "userId": "6ac4d722de4f3b4a1cd351a3"
}

### Test validation error (content minLength <5)
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": true
}