POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true,
  "userId": "6ac4d722de4f3b4a1cd351a3"
}

### Test validation error (content minLength <5)
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": true
}